### ISSUE TITLE
[Feature Request] New Image API features

### ISSUE THREAD

**Issue by jeppes** [armada-ths/ais#38]
Given the importance of imagery in the frontend clients, I really think we should invest time into re-thinking how pictures are handled and served in the api. I've therefore put together this list of features. I've ranked in order of how important I think the features are (Most important first, least important last)
- Better Image compression and sizing. Maybe the ability to specify webp formats (although I realize that this would probably only be useful on android and in chrome)
- Smaller logos https://github.com/armada-ths/ais/issues/32.
- Sending a hex color code along with each image to be used as a placeholder when it loads.
- Remove logo_square_url. 
- Sending the height and width of the image so that space can be allocated before it is loaded
- Ability to request smaller or more compressed images.

**Comment by mictab** [comment]
Anything new here? :-) @armada-ths/system-developers
