### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by mictab** [armada-ths/ais#40]
No reason not to now that `ais` is non-private and therefore Travis is free.

**Comment by macaullyjames** [comment]
Sounds good to me! 👍

**Comment by svenanderzen** [comment]
Saw that someone had gone ahead and enabled testing at https://travis-ci.org/ so I've pushed a basic .travis.yml file for a Django project ( #2eab63a3664669565234099bb062b2202efc0ce5 ). I'm no Travis-CI guru at all, so if someone could check if it's not all crap that would be great :+1: .

At least it's not running with the ruby default now :)

Now we just have to fix all the test errors... <3
