### ISSUE TITLE
[Feature Request] Banquet placement endpoints

### ISSUE THREAD

**Issue by apals** [armada-ths/ais#76]
Hi. The mobile apps will need the url to an endpoint where we can get information about banquet placement. Ideally, we'd also be able to get some other information about the people as well, e.g. LinkedIn profile link. The URL to the image of the banquet map will also be needed somewhere.

**Comment by jakobivarsson** [comment]
Will we have some kind of registration for the banquet? In that case where (ais or third party)?
If we have the registration data in ais, then it would be an easy task to place the participants and serve the placements through the API.

**Comment by mictab** [comment]
Registration in AIS.
