### ISSUE TITLE
Change http://anmalan.armada.nu/ to http://register.armada.nu/

### ISSUE THREAD

**Issue by Tiseno** [armada-ths/ais#79]
Delete http://anmalan.armada.nu/ please.
http://register.armada.nu/ exists and should be the default.

**Comment by apals** [comment]
register.armada.nu redirects to anmalan.armada.nu and some of the libraries used can't handle that

**Comment by Milvan** [comment]
The functionality is now moved to ais. Companies will register in ais.armada.nu/register register.armada.nu redirects with DNS configs in gleSys to ais.armada.nu/register
