### ISSUE TITLE
VS code format on save breaks .html files

### ISSUE THREAD

**Issue by e-martinsson** [armada-ths/ais#854]
.vscode/settings.json sets format on save to true, meaning files you're working on formats automatically when you save them. This is a problem, because this autoformatting will break certain .html files. An example is templates/companies/companies_list.html. The current workaround is to disable formatting on save in .vscode/settings.json while working on html files, but it would be nice if there was a way to fix the autoformatting so it formats without breaking the html files

**Comment by didrikmunther** [comment]
https://github.com/armada-ths/ais/pull/1027
