### ISSUE TITLE
Uppdatera pris från AIS

### ISSUE THREAD

**Issue by BingHawk** [armada-ths/ais#912]
När säljaren går in i AIS och justerar pris på en produkt så ska detta synas i dashboarden. 

Nivå 1 är att säljaren sk kunna lägga till en order som då ska få det pris som säljaren skriver (även om inte samma som standard priset.)

Sälj vill också kunna ha två priser, ett för de som signerat IR och ett för de som inte har gjort det. Det är ok om säljaren själv måste gå in och husarers priserna för att det sk funka. Dock ska det då gå att ändra priset på en produkt från ais utan att produken läggs till k företagets beställning. 

//Leo

**Comment by Hampfh** [comment]
Level 1 solved here: fc9e412d317caed2c42f34b4e2882fccccd57a13

**Comment by didrikmunther** [comment]
Level 2 solved.

However, a seller cannot change the price on the cart items, they will get overwritten when the customer adds the item again. To overwrite a price for a product, you must do it after they've submitted the final registration.
